baseURL = "https://goofy-lamarr-58dea5.netlify.com/"
languageCode = "en-us"
title = "Hugo Grayscale Theme"
theme = "hugograyscale"
#googleAnalytics = ""
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
    # Provide some metadata for search and indexing services
    description = "A port of the Grayscale theme to Hugo"
    favicon = "favicon.ico"

[Author]
    name = "RunningStream"
    email = "dco@runningstream.net"

[Social]
    twitter = "stream_running"
