baseURL = "https://goofy-lamarr-58dea5.netlify.com/"
languageCode = "en-us"
title = "Hugo Grayscale Theme"
theme = "hugograyscale"
#googleAnalytics = ""
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
    # Provide some metadata for search and indexing services
    description = "goat.camp yurt.goat.camp We build and sell handmade yurts in the Finger Lakes Region of Upstate New York"
    favicon = "favicon.ico"

[Author]
    name = "Fern Hill"
    email = "segg@tuta.io"

[Social]
    #twitter = "stream_running"
